fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .vscode
      - id: end-of-file-fixer
      - id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'  # Using the older version since you specified types_or
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]
        types_or: [c, c++, cuda, proto]  # Removed textproto
